### ISSUE TITLE
Run on mdslib-1.68.0

### ISSUE THREAD

**Issue by bertacchif** [Johan-dutoit/react-native-movesense#19]
Hi, the project looks really promising, and it would be nice to have this simple access to the Memsense sensors.

I'm trying to start a new project using your library.
I followed the installation steps, fixed some errors, and now, after compilation, the app will just close immediately with no errors.

Here are some more details:

I'm using react native 0.69.3, android 12(32), and min 4.3(18). The movesense release I downloaded is mdslib-1.68.0(1)-release.aar.

To compile, I had to add some settings to **android/app/build.gradle**:

```
android {
	packagingOptions {
		pickFirst 'lib/arm64-v8a/libc++_shared.so'
		pickFirst 'lib/x86/libc++_shared.so'
		pickFirst 'lib/armeabi-v7a/libc++_shared.so'
	}
	...
}
```

This project is now two years old, and I'm wondering if you plan to keep upgrading to the latest versions of OS and Memsense. The startup I'm working for would be interested in using this library. Is there any way we can get in contact?

Thanks

**Comment by francescowurq** [comment]
I used logcat to see why the app is crushing, and this is the output:

```
2022-08-02 12:13:39.471 7960-8007/com.everactive E/SDSInternalWrapper: System.loadLibrary(mds) FAILED! Error: sds: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__sfp_handle_exceptions" referenced by "/data/app/~~vFuLDQArHekRSLrNHBkdSA==/com.everactive-4qudHMz5hnaPzVAmFAbSNw==/lib/arm64/libmds.so"...
2022-08-02 12:13:39.473 7960-8007/com.everactive E/com.everactive: No implementation found for void com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(java.lang.Object) (tried Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate and Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate__Ljava_lang_Object_2)
    
    --------- beginning of crash
2022-08-02 12:13:39.474 7960-8007/com.everactive E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.everactive, PID: 7960
    java.lang.UnsatisfiedLinkError: No implementation found for void com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(java.lang.Object) (tried Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate and Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate__Ljava_lang_Object_2)
        at com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(Native Method)
        at com.movesense.mds.SDSInternalWrapper.setDelegate(SDSInternalWrapper.java:167)
        at com.movesense.mds.internal.operation.MdsOperationHandler.<init>(MdsOperationHandler.java:87)
        at com.movesense.mds.Mds$Builder.build(Mds.java:383)
        at com.mdsrn.RNMdsModule.<init>(RNMdsModule.java:39)
        at com.mdsrn.RNMdsPackage.createNativeModules(RNMdsPackage.java:16)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:920)
```

I found an issue on Movesense's repository, related to compiling for the right architecture, but I'm not sure this is the same problem.

https://bitbucket.org/movesense/movesense-mobile-lib/issues/81/movesense-ecg-sample-keeps-stopping

**Comment by bertacchif** [comment]
I used logcat to debug exactly what is causing the crash, and this is the error message:

```
2022-08-02 12:13:39.471 7960-8007/com.everactive E/SDSInternalWrapper: System.loadLibrary(mds) FAILED! Error: sds: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__sfp_handle_exceptions" referenced by "/data/app/~~vFuLDQArHekRSLrNHBkdSA==/com.everactive-4qudHMz5hnaPzVAmFAbSNw==/lib/arm64/libmds.so"...
2022-08-02 12:13:39.473 7960-8007/com.everactive E/com.everactive: No implementation found for void com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(java.lang.Object) (tried Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate and Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate__Ljava_lang_Object_2)
    
    --------- beginning of crash
2022-08-02 12:13:39.474 7960-8007/com.everactive E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.everactive, PID: 7960
    java.lang.UnsatisfiedLinkError: No implementation found for void com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(java.lang.Object) (tried Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate and Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate__Ljava_lang_Object_2)
        at com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(Native Method)
        at com.movesense.mds.SDSInternalWrapper.setDelegate(SDSInternalWrapper.java:167)
        at com.movesense.mds.internal.operation.MdsOperationHandler.<init>(MdsOperationHandler.java:87)
        at com.movesense.mds.Mds$Builder.build(Mds.java:383)
        at com.mdsrn.RNMdsModule.<init>(RNMdsModule.java:39)
        at com.mdsrn.RNMdsPackage.createNativeModules(RNMdsPackage.java:16)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:920)
```

I found an issue on Movesense's repository that mention the same error, but I'm not sure this is the same problem.

https://bitbucket.org/movesense/movesense-mobile-lib/issues/81/movesense-ecg-sample-keeps-stopping

**Comment by Johan-dutoit** [comment]
Hey, I unfortunately don't use this library anymore (which is why it is 2 years old).  That being said, if you're keen on using it/updating it, more than happy to help merge PRs, etc.
